/-
Copyright (c) 2017 Microsoft Corporation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: Gabriel Ebner
-/

-- This `config_vars.lean` file is automatically generated by cmake from `config_vars.lean.in`.

namespace leanpkg

namespace lean_version

def major : ℕ := 3
def minor : ℕ := 2
def patch : ℕ := 1
def is_release : bool := 0 ≠ 0

end lean_version

end leanpkg
